### ISSUE TITLE
Add name and Link to your GitHub account.

### ISSUE THREAD

**Issue by susanmaharjan** [AzharAlali/Kali-Linux-for-Digital-Forensics#1]
Add your name and link to your GitHub account in README. Add a comment in this issue when you are working. Then add a comment in this issue when you are done. This is to not have a merge conflict. We will be doing this whenever we are working. Once both of you are done, I will close the issue.

**Comment by samueleagan** [comment]
Name updated.

**Comment by AzharAlali** [comment]
I just did, thanks
